01.--Which department has the highest number of appointments 
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
ORDER BY
	TOTAL_APPOINTMENTS DESC

02.--Which department have the highest appointments workload per doctor?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APOINTMEANTS,
	COUNT(DISTINCT DOC.DOCTOR_ID) AS TOTAL_DOCTORS,
	ROUND(
		COUNT(A.APPOINTMENT_ID)::NUMERIC / COUNT(DISTINCT DOC.DOCTOR_ID),
		2
	) AS APPOINTMENT_PER_DOCTORS
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME

03.--Which doctors have a high appointments workload compared with the overall average?
WITH
	DOCTOR_WORKLOAD AS (
		SELECT
			DOC.DOCTOR_ID,
			DOC.DOCTOR_NAME,
			D.DEPARTMENT_NAME,
			COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENT
		FROM
			DOCTORS DOC
			JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
			LEFT JOIN APPOINTMENTS A ON DOC.DOCTOR_ID = A.DOCTOR_ID
		GROUP BY
			DOC.DOCTOR_ID,
			DOC.DOCTOR_NAME,
			D.DEPARTMENT_NAME
	),
	AVERAGE_WORKLOAD AS (
		SELECT
			AVG(TOTAL_APPOINTMENT) AS AVG_APPOINTMENTS
		FROM
			DOCTOR_WORKLOAD
	)
SELECT
	DOCTOR_ID,
	DOCTOR_NAME,
	DEPARTMENT_NAME,
	TOTAL_APPOINTMENT,
	ROUND(
		(
			SELECT
				AVG_APPOINTMENTS
			FROM
				AVERAGE_WORKLOAD
		),
		2
	) AS AVERAGE_APPOINTMENTS,
	CASE
		WHEN TOTAL_APPOINTMENT > (
			SELECT
				AVG_APPOINTMENTS
			FROM
				AVERAGE_WORKLOAD
		) THEN 'High loaded'
		ELSE 'Normal loaded'
	END AS WORKLOAD_CATEGORY
FROM
	DOCTOR_WORKLOAD
ORDER BY
	TOTAL_APPOINTMENT DESC;

04.--top 10 busiest doctors 
SELECT
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM
	DOCTORS DOC
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
	JOIN APPOINTMENTS A ON DOC.DOCTOR_ID = A.DOCTOR_ID
GROUP BY
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME
ORDER BY
	TOTAL_APPOINTMENTS DESC
LIMIT
	10;
05.-- Which department have more than 6,000 appointments 
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENT
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON DOC.DOCTOR_ID = A.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	COUNT(A.APPOINTMENT_ID) > 6000

06.--Which doctors have handled more than 580 appointments, and which department does each doctors belong to ?
SELECT
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENT
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON DOC.DOCTOR_ID = A.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME
HAVING
	COUNT(A.APPOINTMENT_ID) > 580

07-- Which departments have an average waiting time greater than 28 minutes?
SELECT
	D.DEPARTMENT_NAME,
	ROUND(AVG(A.WAITING_TIME_MINUTES), 2) AS AVG_WAITING_TIME
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	AVG(A.WAITING_TIME_MINUTES) > 28
ORDER BY
	AVG_WAITING_TIME DESC;

08.--Which appointment types have an average waiting time greater than 28 minutes?
SELECT
	A.APPOINTMENT_TYPE,
	ROUND(AVG(A.WAITING_TIME_MINUTES), 2) AS AVG_WAITING_TIME
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	A.APPOINTMENT_TYPE
HAVING
	AVG(A.WAITING_TIME_MINUTES) > 28
ORDER BY
	AVG_WAITING_TIME DESC;

09.--Which doctors have an average waiting time greater than 30 minutes and handled at least 500 appointments?
SELECT
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
	ROUND(AVG(WAITING_TIME_MINUTES), 2) AS AVERAGE_TIME
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME
HAVING
	AVG(WAITING_TIME_MINUTES) > 30
	AND COUNT(A.APPOINTMENT_ID) >= 500
ORDER BY
	TOTAL_APPOINTMENTS DESC
10.--Which departments have a readmission rate greater than 10%?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.ADMISSION_ID) AS TOTAL_ADMISSION,
	COUNT(
		CASE
			WHEN A.READMISSION_FLAG = TRUE THEN 1
		END
	) AS READMISSIONS,
	ROUND(
		COUNT(
			CASE
				WHEN A.READMISSION_FLAG = TRUE THEN 1
			END
		)::NUMERIC / COUNT(A.ADMISSION_ID) * 100,
		2
	) AS READMISSION_RATE
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	ROUND(
		COUNT(
			CASE
				WHEN A.READMISSION_FLAG = TRUE THEN 1
			END
		)::NUMERIC / COUNT(A.ADMISSION_ID) * 100,
		2
	) > 10
ORDER BY
	READMISSION_RATE DESC
11.-- which admission types have an average length of stay greater than 4 days?
SELECT
	A.ADMISSION_TYPE,
	ROUND(AVG(A.LENGTH_OF_STAY), 2) AS AVERAGE_STAY
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	A.ADMISSION_TYPE
HAVING
	ROUND(AVG(A.LENGTH_OF_STAY), 2) > 4

12.--Which departments have an average length of stay greater than 4 days and a readmission rate greater than 10 ?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.ADMISSION_ID) AS TOTAL_ADMISSION,
	ROUND(
		COUNT(
			CASE
				WHEN A.READMISSION_FLAG = TRUE THEN 1
			END
		),
		2
	) AS READMISSION,
	ROUND(AVG(A.LENGTH_OF_STAY), 2) AS AVERAGE_LENGTH,
	ROUND(
		COUNT(
			CASE
				WHEN A.READMISSION_FLAG = TRUE THEN 1
			END
		)::NUMERIC / COUNT(A.ADMISSION_ID) * 100,
		2
	) AS READMISSION_RATE
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	ROUND(AVG(A.LENGTH_OF_STAY), 2) > 4
	AND COUNT(
		CASE
			WHEN A.READMISSION_FLAG = TRUE THEN 1
		END
	)::NUMERIC / COUNT(A.ADMISSION_ID) * 100 > 10
ORDER BY
	READMISSION_RATE DESC

13.--which doctors have an average patient satisfaction score below 4.5 and at least 500 completed appointments?
SELECT
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS COMPLETED_APPOINTMENTS,
	ROUND(AVG(A.SATISFACTION_SCORE), 2) AS AVG_SATISFACTION
FROM
	DOCTORS DOC
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
	JOIN APPOINTMENTS A ON DOC.DOCTOR_ID = A.DOCTOR_ID
WHERE
	A.APPOINTMENT_STATUS = 'Completed'
GROUP BY
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME
HAVING
	AVG(A.SATISFACTION_SCORE) < 4.5
	AND COUNT(A.APPOINTMENT_ID) >= 500
ORDER BY
	AVG_SATISFACTION;
--No doctors had both an average satisfaction score below 4.5 and at least 500 completed appointments 
14.--Which treatment types have an average treatment cost greater than 4000 and an average treatment duration greater than 
--80 minutes
SELECT
	TREATMENT_TYPE,
	ROUND(AVG(TREATMENT_COST), 2) AS AVERAGE_COST,
	ROUND(AVG(TREATMENT_DURATION_MINUTES), 2) AS AVERAGE_MIN
FROM
	TREATMENTS
GROUP BY
	TREATMENT_TYPE
HAVING
	AVG(TREATMENT_COST) > 4000
	AND AVG(TREATMENT_DURATION_MINUTES) < 80
--No treatment_type meets both conditions simultaneously 

15.--Which treatment types have a treatment success rate above 70%?
SELECT
	TREATMENT_TYPE,
	COUNT(TREATMENT_ID) AS COUNT_TREATMENT,
	COUNT(
		CASE
			WHEN TREATMENT_OUTCOME = 'Improved' THEN 1
		END
	) AS IMPROVED_COUNT,
	ROUND(
		COUNT(
			CASE
				WHEN TREATMENT_OUTCOME = 'Improved' THEN 1
			END
		)::NUMERIC / COUNT(TREATMENT_ID) * 100,
		2
	) AS SUCCESS_RATE
FROM
	TREATMENTS
GROUP BY
	TREATMENT_TYPE
HAVING
	COUNT(
		CASE
			WHEN TREATMENT_OUTCOME = 'Improved' THEN 1
		END
	)::NUMERIC / COUNT(TREATMENT_ID) * 100 > 70

16.--which department have more than 1000 admission and an average length of stay greater than 4 days?
SELECT
	DEPARTMENT_NAME,
	COUNT(ADMISSION_ID) AS TOTAL_ADMISSION,
	ROUND(AVG(A.LENGTH_OF_STAY), 2) AS AVERAGE_MIN
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = A.DEPARTMENT_ID
GROUP BY
	DEPARTMENT_NAME
HAVING
	COUNT(ADMISSION_ID) > 1000
	AND AVG(A.LENGTH_OF_STAY) > 4

17.--which doctors have more than 580 appointments and an average waiting time greater than 30 minutes? 
SELECT
	DOCTOR_ID,
	COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENT,
	ROUND(AVG(WAITING_TIME_MINUTES), 2) AS AVERAGE_TIME
FROM
	APPOINTMENTS
GROUP BY
	DOCTOR_ID
HAVING
	COUNT(APPOINTMENT_ID) > 580
	AND AVG(WAITING_TIME_MINUTES) > 30

18.--Which department have more than 1000 admissions and readmission rate above 10 ?
SELECT
	DEPARTMENT_NAME,
	COUNT(ADMISSION_ID) AS TOTAL_ADMISSION,
	COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	) AS ONLY_TRUE,
	ROUND(
		COUNT(
			CASE
				WHEN READMISSION_FLAG = 'true' THEN 1
			END
		)::NUMERIC / COUNT(ADMISSION_ID) * 100,
		2
	) AS RATE
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = A.DEPARTMENT_ID
GROUP BY
	DEPARTMENT_NAME
HAVING
	COUNT(ADMISSION_ID) > 1000
	AND COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	)::NUMERIC / COUNT(ADMISSION_ID) * 100 > 10
19. --Which doctors handle more than 550 appointments and have an average waiting time below 28 minutes?
SELECT
	DOCTOR_ID,
	COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENT,
	ROUND(AVG(WAITING_TIME_MINUTES), 2) AS AVERAGE_TIME
FROM
	APPOINTMENTS
GROUP BY
	DOCTOR_ID
HAVING
	COUNT(APPOINTMENT_ID) > 550
	AND AVG(WAITING_TIME_MINUTES) < 28
20.--which treatment types have an average treatment cost above 3,500 and a success rate above 65%?
SELECT
	TREATMENT_TYPE,
	ROUND(AVG(TREATMENT_COST), 2) AS AVERAGE_COST,
	COUNT(TREATMENT_ID) AS COUNT_TREATMENT,
	COUNT(
		CASE
			WHEN TREATMENT_OUTCOME = 'Improved' THEN 1
		END
	) AS IMPROVED_COUNT,
	ROUND(
		COUNT(
			CASE
				WHEN TREATMENT_OUTCOME = 'Improved' THEN 1
			END
		)::NUMERIC / COUNT(TREATMENT_ID) * 100,
		2
	) AS SUCCESS_RATE
FROM
	TREATMENTS
GROUP BY
	TREATMENT_TYPE
HAVING
	AVG(TREATMENT_COST) > 3500
	AND COUNT(
		CASE
			WHEN TREATMENT_OUTCOME = 'Improved' THEN 1
		END
	)::NUMERIC / COUNT(TREATMENT_ID) * 100 > 65
21.--Which departments have an occupancy rate above 68% and more than 1200 admission?
SELECT
	D.DEPARTMENT_NAME,
	D.OCCUPANCY_RATE,
	COUNT(ADMISSION_ID) AS TOTAL_ADMISSION
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME,
	D.OCCUPANCY_RATE
HAVING
	D.OCCUPANCY_RATE > 68
	AND COUNT(ADMISSION_ID) > 1200
22.--For each department,find the doctor with the highest number of appointments?
WITH
	DOCTOR_APPOINTMENTS AS (
		SELECT
			D.DEPARTMENT_NAME,
			A.DOCTOR_ID,
			COUNT(AP.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
		FROM
			ADMISSIONS A
			JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
			JOIN APPOINTMENTS AP ON AP.DOCTOR_ID = A.DOCTOR_ID
		GROUP BY
			D.DEPARTMENT_NAME,
			A.DOCTOR_ID
	),
	RANKED_DOCTORS AS (
		SELECT
			*,
			RANK() OVER (
				PARTITION BY
					DEPARTMENT_NAME
				ORDER BY
					TOTAL_APPOINTMENTS DESC
			) AS DOCTOR_RANK
		FROM
			DOCTOR_APPOINTMENTS
	)
SELECT
	*
FROM
	RANKED_DOCTORS
WHERE
	DOCTOR_RANK = 1
ORDER BY
	DEPARTMENT_NAME DESC
--23.For each department,find the top 2 doctors based on total appointments?
WITH
	DOCTOR_APPOINTMENTS AS (
		SELECT
			D.DEPARTMENT_NAME,
			A.DOCTOR_ID,
			COUNT(AP.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
		FROM
			ADMISSIONS A
			JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
			JOIN APPOINTMENTS AP ON AP.DOCTOR_ID = A.DOCTOR_ID
		GROUP BY
			D.DEPARTMENT_NAME,
			A.DOCTOR_ID
	),
	RANKED_DOCTORS AS (
		SELECT
			*,
			RANK() OVER (
				PARTITION BY
					DEPARTMENT_NAME
				ORDER BY
					TOTAL_APPOINTMENTS DESC
			) AS DOCTOR_RANK
		FROM
			DOCTOR_APPOINTMENTS
	)
SELECT
	*
FROM
	RANKED_DOCTORS
WHERE
	DOCTOR_RANK <= 2
ORDER BY
	DEPARTMENT_NAME DESC
--24.For each department,calculate the percentage of appointments that the were completed. 
--then show the departments with a completion rate below 80%?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID),
	COUNT(
		CASE
			WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
		END
	) AS TOTAL_COMPLETION,
	ROUND(
		COUNT(
			CASE
				WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
			END
		)::NUMERIC / COUNT(APPOINTMENT_ID) * 100,
		2
	) AS COMPLETION_RATE
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	COUNT(
		CASE
			WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
		END
	)::NUMERIC / COUNT(APPOINTMENT_ID) * 100 < 80
ORDER BY
	COMPLETION_RATE DESC;
--25.For each department,find the doctors who has the highest average waiting time,considering only doctors with at least 
--500 aoointments 
WITH
	AVG_TIME_ID AS (
		SELECT
			D.DEPARTMENT_NAME,
			DOC.DOCTOR_ID,
			COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
			ROUND(AVG(A.WAITING_TIME_MINUTES), 2) AS AVERAGE_WAITING
		FROM
			APPOINTMENTS A
			JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
			JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
		GROUP BY
			D.DEPARTMENT_NAME,
			DOC.DOCTOR_ID
	),
	RANKING_ORDER AS (
		SELECT
			*,
			RANK() OVER (
				PARTITION BY
					DEPARTMENT_NAME
				ORDER BY
					AVERAGE_WAITING DESC
			) AS RANK_TIME
		FROM
			AVG_TIME_ID
	)
SELECT
	*
FROM
	RANKING_ORDER
WHERE
	TOTAL_APPOINTMENTS > 500
	AND RANK_TIME = 1
	--26.Your ranking is based on total appointments, and the average waiting times also match the department-level results 
WITH
	DEPARTMENT_RANK AS (
		SELECT
			D.DEPARTMENT_NAME,
			COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
			ROUND(AVG(A.WAITING_TIME_MINUTES), 2) AS AVERAGE_WAITING
		FROM
			APPOINTMENTS A
			JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
			JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
		GROUP BY
			D.DEPARTMENT_NAME
	)
SELECT
	*,
	RANK() OVER (
		ORDER BY
			TOTAL_APPOINTMENTS DESC
	) AS DEPARTMENT_RANK
FROM
	DEPARTMENT_RANK
--27.For each department,calculate total appointments,completed appointments,completion rate,Rank based on completion rate?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
	COUNT(
		CASE
			WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
		END
	) AS TOTAL_COMPLETION,
	ROUND(
		COUNT(
			CASE
				WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
			END
		)::NUMERIC / COUNT(APPOINTMENT_ID) * 100,
		2
	) AS COMPLETION_RATE,
	RANK() OVER (
		ORDER BY
			COUNT(
				CASE
					WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
				END
			)::NUMERIC / COUNT(APPOINTMENT_ID) * 100 DESC
	) AS RANK_COMPLETION
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
	--28.For each treatment type to calculate total number of trestments, average treatment cost,rank each treatment type based on average treatment cost,highest to lowest?
SELECT
	TREATMENT_TYPE,
	COUNT(TREATMENT_ID) AS TOTAL_TREATMENT,
	ROUND(AVG(TREATMENT_COST), 2) AS AVERAGE_COST,
	RANK() OVER (
		ORDER BY
			AVG(TREATMENT_COST) DESC
	) AS RANKING
FROM
	TREATMENTS
GROUP BY
	TREATMENT_TYPE
	--29.For each month, calculate the total number of appointments and rank the months based on appointment volumne, highest to lowest?
WITH
	MONTH_RANK AS (
		SELECT
			DATE_TRUNC('month', APPOINTMENT_DATE) AS MONTH,
			COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
			RANK() OVER (
				ORDER BY
					COUNT(APPOINTMENT_ID)
			) AS RANK
		FROM
			APPOINTMENTS
		GROUP BY
			DATE_TRUNC('month', APPOINTMENT_DATE)
	)
SELECT
	TO_CHAR(MONTH, 'YYYY-MM') AS MONTH,
	TOTAL_APPOINTMENTS,
	RANK
FROM
	MONTH_RANK
	--30.For each department,to calculate a total admission,average length of stay,readmission count, readmission rate, rank by readmission rate ?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.ADMISSION_ID) AS TOTAL_ADMISSION,
	ROUND(AVG(A.LENGTH_OF_STAY), 2) AS AVERAGE_STAY,
	COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	) AS READMISSION_COUNT,
	ROUND(
		COUNT(
			CASE
				WHEN READMISSION_FLAG = 'true' THEN 1
			END
		)::NUMERIC / COUNT(A.ADMISSION_ID) * 100,
		2
	) AS READMISSION_RATE,
	RANK() OVER (
		ORDER BY
			COUNT(
				CASE
					WHEN READMISSION_FLAG = 'true' THEN 1
				END
			)::NUMERIC / COUNT(A.ADMISSION_ID) * 100 DESC
	) AS RANKING
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	COUNT(A.ADMISSION_ID) > 1000
	--assessement
	--01.Question,Find the top 5 doctors with the highest number of completed appointments 
SELECT
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
	COUNT(
		CASE
			WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
		END
	) AS ONLY_COMPLETED
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME
ORDER BY
	ONLY_COMPLETED DESC
LIMIT
	5
	--02.Find the department with the highest readmission rate, but only consider department with at least 1000 admission?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.ADMISSION_ID),
	COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	) AS TOTAL_READMISSION,
	ROUND(
		COUNT(
			CASE
				WHEN READMISSION_FLAG = 'true' THEN 1
			END
		)::NUMERIC / COUNT(A.ADMISSION_ID) * 100,
		2
	) AS RATING
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	COUNT(A.ADMISSION_ID) >= 1000
ORDER BY
	COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	)::NUMERIC / COUNT(A.ADMISSION_ID) * 100 DESC
	--03.Find the top 5 doctors with the highest average waiting time,but inculde only doctors who have at least 500 appoinments?
SELECT
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME,
	COUNT(APPOINTMENT_ID) AS TOTAL_APPOINTMENT,
	ROUND(AVG(WAITING_TIME_MINUTES), 2) AS AVERAGE_TIME
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	DOC.DOCTOR_ID,
	DOC.DOCTOR_NAME,
	D.DEPARTMENT_NAME
HAVING
	COUNT(APPOINTMENT_ID) >= 500
ORDER BY
	AVG(WAITING_TIME_MINUTES) DESC
LIMIT
	5
	--04.Find the top 3 departments by appointment completion rate?
SELECT
	D.DEPARTMENT_NAME,
	COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENT,
	COUNT(
		CASE
			WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
		END
	) AS ONLY_COMPLETED,
	ROUND(
		COUNT(
			CASE
				WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
			END
		)::NUMERIC / COUNT(A.APPOINTMENT_ID) * 100,
		2
	) AS RATING
FROM
	APPOINTMENTS A
	JOIN DOCTORS DOC ON A.DOCTOR_ID = DOC.DOCTOR_ID
	JOIN DEPARTMENTS D ON DOC.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
ORDER BY
	COUNT(
		CASE
			WHEN A.APPOINTMENT_STATUS = 'Completed' THEN 1
		END
	)::NUMERIC / COUNT(A.APPOINTMENT_ID) * 100 DESC
LIMIT
	3
	--05.Find the department with the highest readmission rate among departments that have more than 1000 admission, average length of stay greater than 4 days ?
SELECT
	D.DEPARTMENT_NAME,
	ROUND(AVG(A.LENGTH_OF_STAY), 2) AS AVERAGE_STAY,
	COUNT(A.ADMISSION_ID) AS TOTAL_ADMISSION,
	COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	) AS TOTAL_READMISSION,
	ROUND(
		COUNT(
			CASE
				WHEN READMISSION_FLAG = 'true' THEN 1
			END
		)::NUMERIC / COUNT(A.ADMISSION_ID) * 100,
		2
	) AS RATING
FROM
	ADMISSIONS A
	JOIN DEPARTMENTS D ON A.DEPARTMENT_ID = D.DEPARTMENT_ID
GROUP BY
	D.DEPARTMENT_NAME
HAVING
	COUNT(A.ADMISSION_ID) > 1000
	AND AVG(A.LENGTH_OF_STAY) > 4
ORDER BY
	COUNT(
		CASE
			WHEN READMISSION_FLAG = 'true' THEN 1
		END
	)::NUMERIC / COUNT(A.ADMISSION_ID) * 100 DESC
	----------------------------------------------SQL ANALYSIS COMPLETED-----------------------------------------------------------------------




